### ISSUE TITLE
Question: can your script handle data from two Teslas ?

### ISSUE THREAD

**Issue by saket424** [mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery#11]
Can you let me know what changes are needed to support t
the 2nd car besides the mqtt base topic of course 

Thanks for your excellent work

**Comment by mekaneck** [comment]
You can duplicate the entire teslamate_create script (lines 16-833) and paste it after the first script ends (line 834). In the duplicated version just change:

- the script name (originally line 16, you could just call it `teslamate_create_2` or something)
- the mqtt base topic (originally line 22)
- and the device name (originally line 25).

That will give you a second script to run, which would create a second device.

**Comment by 10tribu** [comment]
Hello
 i try to add this change but it didn't work for me
can you help me ?

**Comment by mekaneck** [comment]
@10tribu - are you still having issues with this?

**Comment by mekaneck** [comment]
Issue addressed with the re-write of this script. Multiple cars are now simply added as a list.
