### ISSUE TITLE
Adding metric unit for (psi, mi, ft) ?

### ISSUE THREAD

**Issue by dranreb38** [mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery#12]
Thank you for your excellent work. I have a request to make to you, is it possible to add the units of measurement in metric? . 
I tried to modify the script but it doesn't work. Thank you for your help
Thank

**Comment by Walhalla360** [comment]
@dranreb38 @jerr0328

I don't know how to change this script that you can have both options, but what you need to do to get metric units is the following:

You not only have to change the "unit_of_measurement" for each sensor. You also have to remove the conversation calculations part of each "value_template".

Here are all changes I have done with each of it's initial values:

          **sensor_name: Elevation**

          unit_of_measurement: ft
          unit_of_measurement: m

          value_template: (value | float(0) * 3.280839) | round(1)
          value_template: value | round(1)


          **sensor_name: Speed**

          unit_of_measurement: mph
          unit_of_measurement: km/h

          value_template: (value | float(0) / 1.609344) | round(1)
          value_template: value | round(1)


          **sensor_name: Odometer**

          unit_of_measurement: mi
          unit_of_measurement: km

          value_template: (value | float(0) / 1.609344) | round(1)
          value_template: value | round(1)


          **sensor_name: Battery Range**

          unit_of_measurement: mi
          unit_of_measurement: km

          value_template: (value | float(0) / 1.609344) | round(1)
          value_template: value | round(1)


          **sensor_name: Tire Pressure (Front Left)**

          unit_of_measurement: psi
          unit_of_measurement: bar

          value_template: (value | float(0) * 14.503773) | round(1)
          value_template: value | round(1)


          **sensor_name: Tire Pressure (Front Right)**

          unit_of_measurement: psi
          unit_of_measurement: bar

          value_template: (value | float(0) * 14.503773) | round(1)
          value_template: value | round(1)


          **sensor_name: Tire Pressure (Rear Left)**

          unit_of_measurement: psi
          unit_of_measurement: bar

          value_template: (value | float(0) * 14.503773) | round(1)
          value_template: value | round(1)


          **sensor_name: Tire Pressure (Rear Right)**

          unit_of_measurement: psi
          unit_of_measurement: bar

          value_template: (value | float(0) * 14.503773) | round(1)
          value_template: value | round(1)

**Comment by jerr0328** [comment]
Ah I had forgotten to push the branch to my fork, I've pushed the changes I made to get it to work, you don't really want too much rounding for tire pressure in bar: https://github.com/jerr0328/Teslamate-Home-Assistant-MQTT-Autodiscovery/blob/metric_units/teslamate_mqtt_device_creation_script.yaml but likely would need something clever if wanting to keep the two in sync, or having two files in the repo (for metric and imperial) or having a section to add imperial units based off of another sensor.

**Comment by mekaneck** [comment]
Thanks @jerr0328 - that's the correct way to do it.
