### ISSUE TITLE
Device tracker missing Longitude

### ISSUE THREAD

**Issue by mn-box** [mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery#13]
Code:
############ DEVICE TRACKER ############
      - service: script.teslamate_backend
        data:
          sensor_type: device_tracker
          object_id: location
          state_topic_suffix: geofence
          sensor_name: Location
          icon: mdi:car
          json_attributes_template: '{ \"latitude\": value | float(0), \"longitude\": states(\"sensor.{{ entity_prefix }}_longitude\") | float(0) } | tojson'
          json_attributes_topic_suffix: latitude
          source_type: gps
          value_template: \"home\" if value | lower == \"home\"  else \"not_home\"
          device: '{{ device }}'
          discovery_prefix: "{{ discovery_prefix }}"
          base_topic: "{{ base_topic }}"
          suggested_area: "{{ suggested_area }}"
          manufacturer: "{{ manufacturer }}"
          device_name: "{{ device_name }}"

Does not result in lat/long input in device tracker

source_type: gps
latitude: XXX
longitude: 0 <=== zero!
gps_accuracy: 0
icon: mdi:car
friendly_name: Tesla Location

**Comment by mekaneck** [comment]
Is your longitude sensor working?

If you go to settings -> devices & services -> select the MQTT integration -> select 'devices' -> find the device representing your Tesla and click it.

Under 'device info' click on 'MQTT info'

Scroll down until you find the entry for '<your car name> location' for example 'Tesla Model 3 Location'

Under MQTT discovery data: and Topic: -> expand 'Payload'

Copy the entire json_attributes_template and share it here. For example mine is:
```
json_attributes_template: >-
  {{ { "latitude": value | float(0), "longitude":
  states("sensor.tesla_model_3_longitude") | float(0) } | tojson }}
```

**Comment by mekaneck** [comment]
Can you click on the longitude sensor and verify what the `entity_id` is?

Also, have you moved the car since running the script? The location should update any time the latitude sensor is updated.

**Comment by mn-box** [comment]
Sensor is working fine, entity_id: sensor.tesla_longitude

![image](https://github.com/mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery/assets/68974965/1f1b2f93-14ed-407e-8278-9d2b7d6f40fa)

And after a day or so, the long data is now available. I guess I was too impatient? Not sure why lat was working earlier while long not. Thanks again for your quick respond and support.
