### ISSUE TITLE
What is configuration_url? 

### ISSUE THREAD

**Issue by aatifk** [mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery#16]
Apologies for the very dumb question, but in the code where I need to configure my car, it mentions a configuration URL and the serial number. What values are those? Where do I find them? I

**Comment by mekaneck** [comment]
These are both optional (you can delete them entirely if you don't want them).

These will both display in the MQTT device info. I use my car's VIN number as the serial number. And the configuration URL, if configured, will show a "visit" link on that page that will lead to whatever URL you provide. I use the URL of my local teslamate container. 

![image](https://github.com/mekaneck/Teslamate-Home-Assistant-MQTT-Autodiscovery/assets/48502913/f56e2301-4ef8-4c64-900c-87b7073578ff)

**Comment by aatifk** [comment]
Thank you for the prompt response, mate!
